/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.1.441 */
/* Module Version: 5.7 */
/* Tue Dec 17 11:15:39 2019 */

/* parameterized module instance */
clocky __ (.CLKI( ), .CLKOP( ));
