/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.1.441 */
/* Module Version: 5.8 */
/* Wed Dec 11 17:44:26 2019 */

/* parameterized module instance */
MEM __ (.clk( ), .reset( ), .sclk( ), .datain( ), .q( ));
