/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.1.441 */
/* Module Version: 5.8 */
/* Wed Dec 11 21:08:38 2019 */

/* parameterized module instance */
Memory2 __ (.clk( ), .reset( ), .sclk( ), .datain( ), .q( ));
