/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.1.441 */
/* Module Version: 5.8 */
/* Mon Dec 16 12:30:58 2019 */

/* parameterized module instance */
Memory_SDR __ (.clk( ), .reset( ), .sclk( ), .datain( ), .q( ));
