//Verilog testbench template generated by SCUBA Diamond (64-bit) 3.11.1.441
`timescale 1 ns / 1 ps
module tb;
    reg [15:0] Din = 16'b0;
    reg Clock = 0;
    reg ClockEn = 0;
    reg Reset = 0;
    wire [15:0] Q;

    integer i0 = 0, i1 = 0, i2 = 0, i3 = 0, i4 = 0;

    GSR GSR_INST (.GSR(1'b1));
    PUR PUR_INST (.PUR(1'b1));

    Memory_Shift u1 (.Din(Din), .Clock(Clock), .ClockEn(ClockEn), .Reset(Reset), 
        .Q(Q)
    );

    initial
    begin
       Din <= 0;
      #100;
      @(Reset == 1'b0);
      for (i1 = 0; i1 < 19; i1 = i1 + 1) begin
        @(posedge Clock);
        #1  Din <= Din + 1'b1;
      end
    end
    always
    #5.00 Clock <= ~ Clock;

    initial
    begin
       ClockEn <= 1'b0;
      #100;
      @(Reset == 1'b0);
       ClockEn <= 1'b1;
    end
    initial
    begin
       Reset <= 1'b1;
      #100;
       Reset <= 1'b0;
    end
endmodule